# Generated by Django 4.1.7 on 2023-02-23 17:27

import app.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last name')),
                ('sex', models.CharField(choices=[('nc', 'not choisen'), ('m', 'man'), ('w', 'woman')], default='nc', max_length=8, verbose_name='sex')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('position', models.CharField(max_length=128, verbose_name='position')),
                ('status', models.CharField(choices=[('s', 'in search of a job'), ('n', 'not looking for a job'), ('t', 'Offered a job while Im thinking')], default='s', max_length=8, verbose_name='resume status')),
                ('salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='salary')),
                ('education', models.TextField(blank=True, null=True, verbose_name='education')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='skills')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about candidate')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='candidate phone')),
                ('tg', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='company title')),
                ('employees', models.IntegerField(verbose_name='count of employees')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('address', models.CharField(max_length=512, verbose_name='company address')),
                ('site', models.URLField(verbose_name='company site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='company phone')),
                ('tg', models.URLField(verbose_name='telegram')),
                ('about', models.TextField(verbose_name='about company')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('salary', models.PositiveSmallIntegerField(verbose_name='salary in rub')),
                ('skills', models.TextField(verbose_name='necessary skills')),
                ('description', models.TextField(verbose_name='description')),
                ('img', models.ImageField(blank=True, null=True, upload_to=app.models.upload_to_vacancy, verbose_name='image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128, verbose_name='company title')),
                ('position', models.CharField(max_length=128, verbose_name='position in company')),
                ('start', models.DateField(verbose_name='start of work')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end of work')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.candidate', verbose_name='candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nv', 'not viewed'), ('v', 'viewed'), ('i', 'invite'), ('r', 'rejection')], default='nv', max_length=8, verbose_name='status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='candidate comment')),
                ('cv', models.FileField(upload_to=app.models.upload_to_cv_file, verbose_name='cv file')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='app.candidate', verbose_name='candidate')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='app.vacancy', verbose_name='vacancy')),
            ],
            options={
                'unique_together': {('candidate', 'vacancy')},
            },
        ),
    ]
