# Generated by Django 4.1.7 on 2023-02-24 13:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='company phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='company site'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tg',
            field=models.URLField(blank=True, null=True, verbose_name='telegram'),
        ),
    ]
