# Generated by Django 4.1.7 on 2023-02-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_address_alter_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='required_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='required years of experience'),
        ),
    ]
