# Generated by Django 4.1.7 on 2023-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vacancy_required_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Reaction',
        ),
    ]
