# Generated by Django 4.1.7 on 2023-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_response_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sex',
            field=models.CharField(choices=[('NC', 'Not choisen'), ('MN', 'Man'), ('WN', 'Woman')], default='NC', max_length=8, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('SC', 'In search of a job'), ('NSC', 'Not looking for a job'), ('TH', 'Offered a job while Im thinking')], default='SC', max_length=8, verbose_name='resume status'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.CharField(choices=[('NVD', 'Not viewed'), ('VD', 'Viewed'), ('IV', 'Invite'), ('RJ', 'Rejection')], default='NVD', max_length=8, verbose_name='status'),
        ),
    ]
