version: '3.8'

services:
  app:
    build: ./
    command: bash -c "cd src && python -m gunicorn core.asgi:application -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
#     depends_on:
#       - db

#   db:
#     image: postgres:15.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     ports:
#       - 6432:5432
#     env_file:
#       - .env.dev.db

# volumes:
#   postgres_data:

# command: bash -c "cd src && python -m gunicorn core.asgi:application -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
# command: bash -c "cd src && python -m uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
# command: bash -c "cd src && python manage.py runserver 0.0.0.0:8000"
# command: python src/manage.py runserver 0.0.0.0:8000